theme: jekyll-theme-dinky
logo: https://avatars0.githubusercontent.com/u/46445292
title: preferans-rating-js
description: preferans user rating
show_downloads: "true"
include:
  - "_*_.html"
  - "_*_.*.html"